### ISSUE TITLE
Req: add 'default' catchall to remappings

### ISSUE THREAD

**Issue by mmazur** [philipl/evdevremapkeys#29]
I've seen discussions where people mention that using remappings disables a given modifier key for any use outside evdevremapkeys.
A simple and elegant solution to this would give the option of defining a `default` catchall that would be applied any time an explicit key combo is not defined. Proposed syntax:

```yaml
  modifier_groups:
    caps:
      KEY_H:
      - KEY_LEFT
      KEY_J:
      - KEY_DOWN
      KEY_K:
      - KEY_UP
      KEY_L:
      - KEY_RIGHT
      default:
      - KEY_LEFTMETA
      - KEY
```

Additions:
- `default` – execute whenever the modifier was not used with an explicitly defined key
- `KEY` – resend the key pressed

With the example presented above caps+hjkl works as vim–like navigation everywhere, while on a typical desktop environment e.g. caps+d would be "show desktop" and any other caps+KEY would be easily boundable via your desktop environment or something like xbindkeys.
