### ISSUE TITLE
Remap key to mousewheel

### ISSUE THREAD

**Issue by cjh9** [philipl/evdevremapkeys#39]
Is it possible to remap a key to a mousewheel event?

I'm running this config file:
```
devices:
- input_name: 'Dell KB216 Wired Keyboard'
  input_phys: 'usb-0000:00:14.0-4/input0'
  output_name: remap-kbd
  remappings:
    KEY_W:
    - code: REL_WHEEL
      type: EV_REL
      repeat: true
      value: -1
```

And running with `sudo python evdevremapkeys/evdevremapkeys.py -f config.yaml` but it doesn't seem to work...
