### ISSUE TITLE
device isn't registered if input_fn is set to a symlink

### ISSUE THREAD

**Issue by jdeut** [philipl/evdevremapkeys#42]
i have the following udev rule:
```
SUBSYSTEM=="input", ATTRS{idVendor}=="04d9", ATTRS{idProduct}=="0356", GROUP="input", MODE="0660", SYMLINK+="input/ducky"
```
if i try to register the device with
```
devices:
    - input_fn: '/dev/input/ducky'
      output_name: remap-ducky-kbd
      remappings:
        KEY_Y:
        - KEY_Z
        KEY_Z:
        - KEY_Y
```
`evdevrepampkeys` doesn't recognize the device.
